spring.application.name=document-service
server.port=8083

# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/document_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=7804877524
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# RabbitMQ Configuration
spring.rabbitmq.host=host.docker.internal
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.queue.name=document_process_queue
rabbitmq.exchange.name=document_exchange
rabbitmq.routing.key=document_routing_key

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Storage Configuration
file.upload-dir=${FILE_UPLOAD_DIR:C:/microservices-project/uploads}

# Logging
logging.level.com.example.document=DEBUG

# Actuator & Swagger Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
